dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: "AbznrFgoHt4XLBGDMI3DKAHCWIGIAJvwS6klDJdSubMUauHJG4B2G52CEzdAUhkL5qcIYo2Dk26nuLnVTZQfL70fV1lv8SrK+mt72LiqAYvZI+m1ShNpk4ztQ64bLGxMm+PMAOKE7T4mBQi/7g2LfaaCdRQXU3tb4CDQd7M6I4sD5NafvjAULUZyxB4h8upfJTxgCwvon/wj9BbCK1f/MRqmMG4Q5HbJZ35s4TpL3XSrC9hjGy8E718t/xLGJ11hxG2vWdSk3HkYEJyQfsaBYiEQ4Lj+A7YU/ENbjvA55Ji/kGkU04/TZYEmQLsWJgsr6tepUW1WwSsK6LWvwQ9nFH/eZVHPLMEyTPqP7uphLo/GR9VZCb6JeftQ39dcuK0d25sMFlkglgVlb61xwX4+LrSSyzBmWaC75N7dZ9Jx2c4284MtMm6bzuqlmB+ZknYJghmFGGeJD1KByjh+87o7Z232Ns5uFXEOwrIlbf69cwJsrR/iJWaRgGldF/vYWwkcLfuYTE28pgHUIFqPcnYN+4OYmGwsthbGG5mWn3FLJWJvt7o3XfZQXZmkOwXuQ3gTZs3O4MKqyjWA6sNapm7vxiGJV/ynk7u0q7eSWRhte5nmoYZyVWn3Mbg3ZDKieM1qjn0Hv8r5Kdqu78W5dpauKSZD7qquw1EMHc5dDyDUqgs="